[build]
  command = "npm run build"
  publish = "build/client"

[functions]
  directory = "build/server"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  publish = "build/client"

# Environment variables for build (these will be set in Netlify dashboard)
# NODE_ENV is automatically set by Netlify

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/build/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 